// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/kowabunga-api/client/host"
	"github.com/dalet-oss/kowabunga-api/client/instance"
	"github.com/dalet-oss/kowabunga-api/client/operations"
	"github.com/dalet-oss/kowabunga-api/client/pool"
	"github.com/dalet-oss/kowabunga-api/client/project"
	"github.com/dalet-oss/kowabunga-api/client/region"
	"github.com/dalet-oss/kowabunga-api/client/vnet"
	"github.com/dalet-oss/kowabunga-api/client/zone"
)

// Default kowabunga HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new kowabunga HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Kowabunga {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new kowabunga HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Kowabunga {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new kowabunga client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Kowabunga {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Kowabunga)
	cli.Transport = transport
	cli.Host = host.New(transport, formats)
	cli.Instance = instance.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Pool = pool.New(transport, formats)
	cli.Project = project.New(transport, formats)
	cli.Region = region.New(transport, formats)
	cli.Vnet = vnet.New(transport, formats)
	cli.Zone = zone.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Kowabunga is a client for kowabunga
type Kowabunga struct {
	Host host.ClientService

	Instance instance.ClientService

	Operations operations.ClientService

	Pool pool.ClientService

	Project project.ClientService

	Region region.ClientService

	Vnet vnet.ClientService

	Zone zone.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Kowabunga) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Host.SetTransport(transport)
	c.Instance.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Pool.SetTransport(transport)
	c.Project.SetTransport(transport)
	c.Region.SetTransport(transport)
	c.Vnet.SetTransport(transport)
	c.Zone.SetTransport(transport)
}
