// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RebootInstanceOKCode is the HTTP code returned for type RebootInstanceOK
const RebootInstanceOKCode int = 200

/*
RebootInstanceOK The virtual machine has been rebooted successfully.

swagger:response rebootInstanceOK
*/
type RebootInstanceOK struct {
}

// NewRebootInstanceOK creates RebootInstanceOK with default headers values
func NewRebootInstanceOK() *RebootInstanceOK {

	return &RebootInstanceOK{}
}

// WriteResponse to the client
func (o *RebootInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RebootInstanceNotFoundCode is the HTTP code returned for type RebootInstanceNotFound
const RebootInstanceNotFoundCode int = 404

/*
RebootInstanceNotFound Invalid instance ID was provided.

swagger:response rebootInstanceNotFound
*/
type RebootInstanceNotFound struct {
}

// NewRebootInstanceNotFound creates RebootInstanceNotFound with default headers values
func NewRebootInstanceNotFound() *RebootInstanceNotFound {

	return &RebootInstanceNotFound{}
}

// WriteResponse to the client
func (o *RebootInstanceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RebootInstanceInternalServerErrorCode is the HTTP code returned for type RebootInstanceInternalServerError
const RebootInstanceInternalServerErrorCode int = 500

/*
RebootInstanceInternalServerError An error occurred when trying to reboot the virtual machine.

swagger:response rebootInstanceInternalServerError
*/
type RebootInstanceInternalServerError struct {
}

// NewRebootInstanceInternalServerError creates RebootInstanceInternalServerError with default headers values
func NewRebootInstanceInternalServerError() *RebootInstanceInternalServerError {

	return &RebootInstanceInternalServerError{}
}

// WriteResponse to the client
func (o *RebootInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
