// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SuspendInstanceHandlerFunc turns a function with the right signature into a suspend instance handler
type SuspendInstanceHandlerFunc func(SuspendInstanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SuspendInstanceHandlerFunc) Handle(params SuspendInstanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SuspendInstanceHandler interface for that can handle valid suspend instance params
type SuspendInstanceHandler interface {
	Handle(SuspendInstanceParams, interface{}) middleware.Responder
}

// NewSuspendInstance creates a new http.Handler for the suspend instance operation
func NewSuspendInstance(ctx *middleware.Context, handler SuspendInstanceHandler) *SuspendInstance {
	return &SuspendInstance{Context: ctx, Handler: handler}
}

/*
	SuspendInstance swagger:route POST /instance/{instanceId}/suspend instance suspendInstance

Perform a virtual machine software PM suspend.
*/
type SuspendInstance struct {
	Context *middleware.Context
	Handler SuspendInstanceHandler
}

func (o *SuspendInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSuspendInstanceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
