// Code generated by go-swagger; DO NOT EDIT.

package adapter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAdapterOKCode is the HTTP code returned for type DeleteAdapterOK
const DeleteAdapterOKCode int = 200

/*
DeleteAdapterOK The network adapter has been successfully removed.

swagger:response deleteAdapterOK
*/
type DeleteAdapterOK struct {
}

// NewDeleteAdapterOK creates DeleteAdapterOK with default headers values
func NewDeleteAdapterOK() *DeleteAdapterOK {

	return &DeleteAdapterOK{}
}

// WriteResponse to the client
func (o *DeleteAdapterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAdapterNotFoundCode is the HTTP code returned for type DeleteAdapterNotFound
const DeleteAdapterNotFoundCode int = 404

/*
DeleteAdapterNotFound Invalid network adapter ID was provided.

swagger:response deleteAdapterNotFound
*/
type DeleteAdapterNotFound struct {
}

// NewDeleteAdapterNotFound creates DeleteAdapterNotFound with default headers values
func NewDeleteAdapterNotFound() *DeleteAdapterNotFound {

	return &DeleteAdapterNotFound{}
}

// WriteResponse to the client
func (o *DeleteAdapterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteAdapterConflictCode is the HTTP code returned for type DeleteAdapterConflict
const DeleteAdapterConflictCode int = 409

/*
DeleteAdapterConflict The network adapter is not empty or still being referenced.

swagger:response deleteAdapterConflict
*/
type DeleteAdapterConflict struct {
}

// NewDeleteAdapterConflict creates DeleteAdapterConflict with default headers values
func NewDeleteAdapterConflict() *DeleteAdapterConflict {

	return &DeleteAdapterConflict{}
}

// WriteResponse to the client
func (o *DeleteAdapterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// DeleteAdapterInternalServerErrorCode is the HTTP code returned for type DeleteAdapterInternalServerError
const DeleteAdapterInternalServerErrorCode int = 500

/*
DeleteAdapterInternalServerError Unable to delete network adapter.

swagger:response deleteAdapterInternalServerError
*/
type DeleteAdapterInternalServerError struct {
}

// NewDeleteAdapterInternalServerError creates DeleteAdapterInternalServerError with default headers values
func NewDeleteAdapterInternalServerError() *DeleteAdapterInternalServerError {

	return &DeleteAdapterInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteAdapterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
