consumes:
- application/json
info:
  description: Kvm Orchestrator With A BUNch of Goods Added
  title: Kowabunga
  version: 0.5.6
produces:
- application/json
schemes:
- http
basePath: "/api/v1"
swagger: "2.0"

securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token

security:
  - key: []

definitions:
  principal:
    type: string
