// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTemplateHandlerFunc turns a function with the right signature into a get template handler
type GetTemplateHandlerFunc func(GetTemplateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTemplateHandlerFunc) Handle(params GetTemplateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTemplateHandler interface for that can handle valid get template params
type GetTemplateHandler interface {
	Handle(GetTemplateParams, interface{}) middleware.Responder
}

// NewGetTemplate creates a new http.Handler for the get template operation
func NewGetTemplate(ctx *middleware.Context, handler GetTemplateHandler) *GetTemplate {
	return &GetTemplate{Context: ctx, Handler: handler}
}

/*
	GetTemplate swagger:route GET /template/{templateId} template getTemplate

Returns a description of the volume template.
*/
type GetTemplate struct {
	Context *middleware.Context
	Handler GetTemplateHandler
}

func (o *GetTemplate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTemplateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
