/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: csops@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A KGW VPC Network IP zone settings.
 */
export interface KGWVpcNetIpZone { 
    /**
     * The KGW (Kowabunga Network Gateway) zone name (read-only).
     */
    zone: string;
    /**
     * The KGW (Kowabunga Network Gateway) zone gateway private IP address in VPC peered subnet  (read-only).
     */
    _private: string;
}

