/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.10.0
 * Contact: csops@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Region { 
    /**
     * The region ID (auto-generated).
     */
    id?: string;
    /**
     * The region name.
     */
    name: string;
    /**
     * The region description.
     */
    description?: string;
}

