// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAllRegionsHandlerFunc turns a function with the right signature into a get all regions handler
type GetAllRegionsHandlerFunc func(GetAllRegionsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllRegionsHandlerFunc) Handle(params GetAllRegionsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllRegionsHandler interface for that can handle valid get all regions params
type GetAllRegionsHandler interface {
	Handle(GetAllRegionsParams, interface{}) middleware.Responder
}

// NewGetAllRegions creates a new http.Handler for the get all regions operation
func NewGetAllRegions(ctx *middleware.Context, handler GetAllRegionsHandler) *GetAllRegions {
	return &GetAllRegions{Context: ctx, Handler: handler}
}

/*
	GetAllRegions swagger:route GET /region region getAllRegions

Returns the IDs of registered regions.
*/
type GetAllRegions struct {
	Context *middleware.Context
	Handler GetAllRegionsHandler
}

func (o *GetAllRegions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAllRegionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
