export * from './adapter.service';
import { AdapterService } from './adapter.service';
export * from './agent.service';
import { AgentService } from './agent.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './host.service';
import { HostService } from './host.service';
export * from './instance.service';
import { InstanceService } from './instance.service';
export * from './kce.service';
import { KceService } from './kce.service';
export * from './kfs.service';
import { KfsService } from './kfs.service';
export * from './kgw.service';
import { KgwService } from './kgw.service';
export * from './konvey.service';
import { KonveyService } from './konvey.service';
export * from './netgw.service';
import { NetgwService } from './netgw.service';
export * from './nfs.service';
import { NfsService } from './nfs.service';
export * from './pool.service';
import { PoolService } from './pool.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './record.service';
import { RecordService } from './record.service';
export * from './region.service';
import { RegionService } from './region.service';
export * from './subnet.service';
import { SubnetService } from './subnet.service';
export * from './template.service';
import { TemplateService } from './template.service';
export * from './token.service';
import { TokenService } from './token.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vnet.service';
import { VnetService } from './vnet.service';
export * from './volume.service';
import { VolumeService } from './volume.service';
export * from './zone.service';
import { ZoneService } from './zone.service';
export const APIS = [AdapterService, AgentService, GroupService, HostService, InstanceService, KceService, KfsService, KgwService, KonveyService, NetgwService, NfsService, PoolService, ProjectService, RecordService, RegionService, SubnetService, TemplateService, TokenService, UserService, VnetService, VolumeService, ZoneService];
