// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstanceRemoteConnectionParams creates a new GetInstanceRemoteConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstanceRemoteConnectionParams() *GetInstanceRemoteConnectionParams {
	return &GetInstanceRemoteConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstanceRemoteConnectionParamsWithTimeout creates a new GetInstanceRemoteConnectionParams object
// with the ability to set a timeout on a request.
func NewGetInstanceRemoteConnectionParamsWithTimeout(timeout time.Duration) *GetInstanceRemoteConnectionParams {
	return &GetInstanceRemoteConnectionParams{
		timeout: timeout,
	}
}

// NewGetInstanceRemoteConnectionParamsWithContext creates a new GetInstanceRemoteConnectionParams object
// with the ability to set a context for a request.
func NewGetInstanceRemoteConnectionParamsWithContext(ctx context.Context) *GetInstanceRemoteConnectionParams {
	return &GetInstanceRemoteConnectionParams{
		Context: ctx,
	}
}

// NewGetInstanceRemoteConnectionParamsWithHTTPClient creates a new GetInstanceRemoteConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstanceRemoteConnectionParamsWithHTTPClient(client *http.Client) *GetInstanceRemoteConnectionParams {
	return &GetInstanceRemoteConnectionParams{
		HTTPClient: client,
	}
}

/*
GetInstanceRemoteConnectionParams contains all the parameters to send to the API endpoint

	for the get instance remote connection operation.

	Typically these are written to a http.Request.
*/
type GetInstanceRemoteConnectionParams struct {

	/* InstanceID.

	   The ID of the virtual machine to query.
	*/
	InstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get instance remote connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstanceRemoteConnectionParams) WithDefaults() *GetInstanceRemoteConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get instance remote connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstanceRemoteConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) WithTimeout(timeout time.Duration) *GetInstanceRemoteConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) WithContext(ctx context.Context) *GetInstanceRemoteConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) WithHTTPClient(client *http.Client) *GetInstanceRemoteConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) WithInstanceID(instanceID string) *GetInstanceRemoteConnectionParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the get instance remote connection params
func (o *GetInstanceRemoteConnectionParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstanceRemoteConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
