// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSuspendInstanceParams creates a new SuspendInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSuspendInstanceParams() *SuspendInstanceParams {
	return &SuspendInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSuspendInstanceParamsWithTimeout creates a new SuspendInstanceParams object
// with the ability to set a timeout on a request.
func NewSuspendInstanceParamsWithTimeout(timeout time.Duration) *SuspendInstanceParams {
	return &SuspendInstanceParams{
		timeout: timeout,
	}
}

// NewSuspendInstanceParamsWithContext creates a new SuspendInstanceParams object
// with the ability to set a context for a request.
func NewSuspendInstanceParamsWithContext(ctx context.Context) *SuspendInstanceParams {
	return &SuspendInstanceParams{
		Context: ctx,
	}
}

// NewSuspendInstanceParamsWithHTTPClient creates a new SuspendInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewSuspendInstanceParamsWithHTTPClient(client *http.Client) *SuspendInstanceParams {
	return &SuspendInstanceParams{
		HTTPClient: client,
	}
}

/*
SuspendInstanceParams contains all the parameters to send to the API endpoint

	for the suspend instance operation.

	Typically these are written to a http.Request.
*/
type SuspendInstanceParams struct {

	/* InstanceID.

	   The ID of the virtual machine to query.
	*/
	InstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the suspend instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SuspendInstanceParams) WithDefaults() *SuspendInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the suspend instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SuspendInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the suspend instance params
func (o *SuspendInstanceParams) WithTimeout(timeout time.Duration) *SuspendInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the suspend instance params
func (o *SuspendInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the suspend instance params
func (o *SuspendInstanceParams) WithContext(ctx context.Context) *SuspendInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the suspend instance params
func (o *SuspendInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the suspend instance params
func (o *SuspendInstanceParams) WithHTTPClient(client *http.Client) *SuspendInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the suspend instance params
func (o *SuspendInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the suspend instance params
func (o *SuspendInstanceParams) WithInstanceID(instanceID string) *SuspendInstanceParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the suspend instance params
func (o *SuspendInstanceParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a swagger request
func (o *SuspendInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
