// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllRegionsParams creates a new GetAllRegionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllRegionsParams() *GetAllRegionsParams {
	return &GetAllRegionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllRegionsParamsWithTimeout creates a new GetAllRegionsParams object
// with the ability to set a timeout on a request.
func NewGetAllRegionsParamsWithTimeout(timeout time.Duration) *GetAllRegionsParams {
	return &GetAllRegionsParams{
		timeout: timeout,
	}
}

// NewGetAllRegionsParamsWithContext creates a new GetAllRegionsParams object
// with the ability to set a context for a request.
func NewGetAllRegionsParamsWithContext(ctx context.Context) *GetAllRegionsParams {
	return &GetAllRegionsParams{
		Context: ctx,
	}
}

// NewGetAllRegionsParamsWithHTTPClient creates a new GetAllRegionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllRegionsParamsWithHTTPClient(client *http.Client) *GetAllRegionsParams {
	return &GetAllRegionsParams{
		HTTPClient: client,
	}
}

/*
GetAllRegionsParams contains all the parameters to send to the API endpoint

	for the get all regions operation.

	Typically these are written to a http.Request.
*/
type GetAllRegionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all regions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllRegionsParams) WithDefaults() *GetAllRegionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all regions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllRegionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all regions params
func (o *GetAllRegionsParams) WithTimeout(timeout time.Duration) *GetAllRegionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all regions params
func (o *GetAllRegionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all regions params
func (o *GetAllRegionsParams) WithContext(ctx context.Context) *GetAllRegionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all regions params
func (o *GetAllRegionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all regions params
func (o *GetAllRegionsParams) WithHTTPClient(client *http.Client) *GetAllRegionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all regions params
func (o *GetAllRegionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllRegionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
