// Code generated by go-swagger; DO NOT EDIT.

package kfs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteKFSOKCode is the HTTP code returned for type DeleteKFSOK
const DeleteKFSOKCode int = 200

/*
DeleteKFSOK The KFS storage volume has been successfully removed.

swagger:response deleteKFSOK
*/
type DeleteKFSOK struct {
}

// NewDeleteKFSOK creates DeleteKFSOK with default headers values
func NewDeleteKFSOK() *DeleteKFSOK {

	return &DeleteKFSOK{}
}

// WriteResponse to the client
func (o *DeleteKFSOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteKFSNotFoundCode is the HTTP code returned for type DeleteKFSNotFound
const DeleteKFSNotFoundCode int = 404

/*
DeleteKFSNotFound Invalid KFS ID was provided.

swagger:response deleteKFSNotFound
*/
type DeleteKFSNotFound struct {
}

// NewDeleteKFSNotFound creates DeleteKFSNotFound with default headers values
func NewDeleteKFSNotFound() *DeleteKFSNotFound {

	return &DeleteKFSNotFound{}
}

// WriteResponse to the client
func (o *DeleteKFSNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteKFSConflictCode is the HTTP code returned for type DeleteKFSConflict
const DeleteKFSConflictCode int = 409

/*
DeleteKFSConflict The KFS storage volume is not empty or still being referenced.

swagger:response deleteKFSConflict
*/
type DeleteKFSConflict struct {
}

// NewDeleteKFSConflict creates DeleteKFSConflict with default headers values
func NewDeleteKFSConflict() *DeleteKFSConflict {

	return &DeleteKFSConflict{}
}

// WriteResponse to the client
func (o *DeleteKFSConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// DeleteKFSInternalServerErrorCode is the HTTP code returned for type DeleteKFSInternalServerError
const DeleteKFSInternalServerErrorCode int = 500

/*
DeleteKFSInternalServerError Unable to delete KFS storage volume.

swagger:response deleteKFSInternalServerError
*/
type DeleteKFSInternalServerError struct {
}

// NewDeleteKFSInternalServerError creates DeleteKFSInternalServerError with default headers values
func NewDeleteKFSInternalServerError() *DeleteKFSInternalServerError {

	return &DeleteKFSInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteKFSInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
