// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateZoneDefaultPoolOKCode is the HTTP code returned for type UpdateZoneDefaultPoolOK
const UpdateZoneDefaultPoolOKCode int = 200

/*
UpdateZoneDefaultPoolOK Returns the updated project resources object.

swagger:response updateZoneDefaultPoolOK
*/
type UpdateZoneDefaultPoolOK struct {
}

// NewUpdateZoneDefaultPoolOK creates UpdateZoneDefaultPoolOK with default headers values
func NewUpdateZoneDefaultPoolOK() *UpdateZoneDefaultPoolOK {

	return &UpdateZoneDefaultPoolOK{}
}

// WriteResponse to the client
func (o *UpdateZoneDefaultPoolOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateZoneDefaultPoolNotFoundCode is the HTTP code returned for type UpdateZoneDefaultPoolNotFound
const UpdateZoneDefaultPoolNotFoundCode int = 404

/*
UpdateZoneDefaultPoolNotFound Invalid zone ID or storage pool ID was provided.

swagger:response updateZoneDefaultPoolNotFound
*/
type UpdateZoneDefaultPoolNotFound struct {
}

// NewUpdateZoneDefaultPoolNotFound creates UpdateZoneDefaultPoolNotFound with default headers values
func NewUpdateZoneDefaultPoolNotFound() *UpdateZoneDefaultPoolNotFound {

	return &UpdateZoneDefaultPoolNotFound{}
}

// WriteResponse to the client
func (o *UpdateZoneDefaultPoolNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateZoneDefaultPoolInternalServerErrorCode is the HTTP code returned for type UpdateZoneDefaultPoolInternalServerError
const UpdateZoneDefaultPoolInternalServerErrorCode int = 500

/*
UpdateZoneDefaultPoolInternalServerError Unable to assign the requested storage pool as zone's default.

swagger:response updateZoneDefaultPoolInternalServerError
*/
type UpdateZoneDefaultPoolInternalServerError struct {
}

// NewUpdateZoneDefaultPoolInternalServerError creates UpdateZoneDefaultPoolInternalServerError with default headers values
func NewUpdateZoneDefaultPoolInternalServerError() *UpdateZoneDefaultPoolInternalServerError {

	return &UpdateZoneDefaultPoolInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateZoneDefaultPoolInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
