/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.42.0
 * Contact: csops@dalet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// Team - A Kowabunga users team.
type Team struct {

	// The Kowabunga users team ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kowabunga users team name.
	Name string `json:"name"`

	// The Kowabunga users team description.
	Description string `json:"description,omitempty"`

	// List of user IDs that are part of the team.
	Users []string `json:"users"`
}

// AssertTeamRequired checks if the required fields are not zero-ed
func AssertTeamRequired(obj Team) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"users": obj.Users,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTeamConstraints checks if the values respects the defined constraints
func AssertTeamConstraints(obj Team) error {
	return nil
}
