/*
 * Kowabunga
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.10.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// HostCapsCpu - the host CPU characteristics
type HostCapsCpu struct {

	// the host CPU architecture
	Arch string `json:"arch"`

	// the host CPU model
	Model string `json:"model"`

	// the host CPU vendor
	Vendor string `json:"vendor"`

	// the host CPU number of sockets
	Sockets int32 `json:"sockets"`

	// the host CPU number of cores
	Cores int32 `json:"cores"`

	// the host CPU number of threads
	Threads int32 `json:"threads"`
}

// AssertHostCapsCpuRequired checks if the required fields are not zero-ed
func AssertHostCapsCpuRequired(obj HostCapsCpu) error {
	elements := map[string]interface{}{
		"arch": obj.Arch,
		"model": obj.Model,
		"vendor": obj.Vendor,
		"sockets": obj.Sockets,
		"cores": obj.Cores,
		"threads": obj.Threads,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertHostCapsCpuConstraints checks if the values respects the defined constraints
func AssertHostCapsCpuConstraints(obj HostCapsCpu) error {
	return nil
}
