/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.41.0
 * Contact: csops@dalet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// Kfs - A Kowabunga File System (KFS) provides an elastic NFS-like remote storage volume.
type Kfs struct {

	// The KFS (Kowabunga File System) ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The KFS (Kowabunga File System) name.
	Name string `json:"name"`

	// The KFS (Kowabunga File System) description.
	Description string `json:"description,omitempty"`

	// The KFS (Kowabunga File System) volume access type.
	Access string `json:"access,omitempty"`

	// The KFS (Kowabunga File System) NFS protocol versions to be supported.
	Protocols []int32 `json:"protocols,omitempty"`

	// The KFS (Kowabunga File System) endpoint FQDN (read-only).
	Endpoint string `json:"endpoint,omitempty"`

	// The KFS (Kowabunga File System) volume bytes used (read-only).
	Size int64 `json:"size,omitempty"`
}

// AssertKfsRequired checks if the required fields are not zero-ed
func AssertKfsRequired(obj Kfs) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKfsConstraints checks if the values respects the defined constraints
func AssertKfsConstraints(obj Kfs) error {
	return nil
}
