/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.30.0
 * Contact: csops@dalet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// HostCaps - A computing host capability.
type HostCaps struct {

	// The computing host CPU characteristics.
	Cpu HostCpu `json:"cpu"`

	// The computing host memory size (bytes).
	Memory int64 `json:"memory"`
}

// AssertHostCapsRequired checks if the required fields are not zero-ed
func AssertHostCapsRequired(obj HostCaps) error {
	elements := map[string]interface{}{
		"cpu": obj.Cpu,
		"memory": obj.Memory,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertHostCapsConstraints checks if the values respects the defined constraints
func AssertHostCapsConstraints(obj HostCaps) error {
	return nil
}
