/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.38.0
 * Contact: csops@dalet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// KgwNetIpZone - A KGW Network IP zone settings.
type KgwNetIpZone struct {

	// The KGW (Kowabunga Network Gateway) zone name (read-only).
	Zone string `json:"zone"`

	// The KGW (Kowabunga Network Gateway) zone gateway public virtual IP (read-only).
	Public string `json:"public"`

	// The KGW (Kowabunga Network Gateway) zone gateway private virtual IP (read-only).
	Private string `json:"private"`
}

// AssertKgwNetIpZoneRequired checks if the required fields are not zero-ed
func AssertKgwNetIpZoneRequired(obj KgwNetIpZone) error {
	elements := map[string]interface{}{
		"zone": obj.Zone,
		"public": obj.Public,
		"private": obj.Private,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKgwNetIpZoneConstraints checks if the values respects the defined constraints
func AssertKgwNetIpZoneConstraints(obj KgwNetIpZone) error {
	return nil
}
