/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.42.0
 * Contact: csops@dalet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server




// Kawaii - A Kawaii (Kowabunga Adapative WAn Intelligent Interface) is a network gateway used for your Internet inbound and outbound traffic.
type Kawaii struct {

	// The Kawaii ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kawaii name.
	Name string `json:"name,omitempty"`

	// The Kawaii description.
	Description string `json:"description,omitempty"`

	// The Kawaii list of assigned virtual IPs per-zone addresses (read-only).
	Netip KawaiiNetIp `json:"netip,omitempty"`

	// The Kawaii firewall settings from/to public Internet).
	Firewall KawaiiFirewall `json:"firewall,omitempty"`

	// The Kawaii list of NAT forwarding entries. Kawaii will forward public Internet traffic from all public virtual IPs to requested private subnet IP addresses.
	Dnat []KawaiiDNatRule `json:"dnat,omitempty"`

	// The Kawaii list of Kowabunga private VPC subnet peering entries.
	VpcPeerings []KawaiiVpcPeering `json:"vpc_peerings,omitempty"`
}

// AssertKawaiiRequired checks if the required fields are not zero-ed
func AssertKawaiiRequired(obj Kawaii) error {
	for _, el := range obj.Dnat {
		if err := AssertKawaiiDNatRuleRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.VpcPeerings {
		if err := AssertKawaiiVpcPeeringRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKawaiiConstraints checks if the values respects the defined constraints
func AssertKawaiiConstraints(obj Kawaii) error {
	return nil
}
