// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteHostParams creates a new DeleteHostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteHostParams() *DeleteHostParams {
	return &DeleteHostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHostParamsWithTimeout creates a new DeleteHostParams object
// with the ability to set a timeout on a request.
func NewDeleteHostParamsWithTimeout(timeout time.Duration) *DeleteHostParams {
	return &DeleteHostParams{
		timeout: timeout,
	}
}

// NewDeleteHostParamsWithContext creates a new DeleteHostParams object
// with the ability to set a context for a request.
func NewDeleteHostParamsWithContext(ctx context.Context) *DeleteHostParams {
	return &DeleteHostParams{
		Context: ctx,
	}
}

// NewDeleteHostParamsWithHTTPClient creates a new DeleteHostParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteHostParamsWithHTTPClient(client *http.Client) *DeleteHostParams {
	return &DeleteHostParams{
		HTTPClient: client,
	}
}

/*
DeleteHostParams contains all the parameters to send to the API endpoint

	for the delete host operation.

	Typically these are written to a http.Request.
*/
type DeleteHostParams struct {

	/* HostID.

	   The ID of the host to delete.
	*/
	HostID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete host params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteHostParams) WithDefaults() *DeleteHostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete host params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteHostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete host params
func (o *DeleteHostParams) WithTimeout(timeout time.Duration) *DeleteHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete host params
func (o *DeleteHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete host params
func (o *DeleteHostParams) WithContext(ctx context.Context) *DeleteHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete host params
func (o *DeleteHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete host params
func (o *DeleteHostParams) WithHTTPClient(client *http.Client) *DeleteHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete host params
func (o *DeleteHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostID adds the hostID to the delete host params
func (o *DeleteHostParams) WithHostID(hostID string) *DeleteHostParams {
	o.SetHostID(hostID)
	return o
}

// SetHostID adds the hostId to the delete host params
func (o *DeleteHostParams) SetHostID(hostID string) {
	o.HostID = hostID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hostId
	if err := r.SetPathParam("hostId", o.HostID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
