// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateVolumeHandlerFunc turns a function with the right signature into a create volume handler
type CreateVolumeHandlerFunc func(CreateVolumeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateVolumeHandlerFunc) Handle(params CreateVolumeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateVolumeHandler interface for that can handle valid create volume params
type CreateVolumeHandler interface {
	Handle(CreateVolumeParams, interface{}) middleware.Responder
}

// NewCreateVolume creates a new http.Handler for the create volume operation
func NewCreateVolume(ctx *middleware.Context, handler CreateVolumeHandler) *CreateVolume {
	return &CreateVolume{Context: ctx, Handler: handler}
}

/*
	CreateVolume swagger:route POST /project/{projectId}/volume project volume createVolume

Creates a new storage volume.
*/
type CreateVolume struct {
	Context *middleware.Context
	Handler CreateVolumeHandler
}

func (o *CreateVolume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateVolumeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
