// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/kowabunga-api/models"
)

// CreateProjectZoneKgwCreatedCode is the HTTP code returned for type CreateProjectZoneKgwCreated
const CreateProjectZoneKgwCreatedCode int = 201

/*
CreateProjectZoneKgwCreated Returns the newly created KGW object.

swagger:response createProjectZoneKgwCreated
*/
type CreateProjectZoneKgwCreated struct {

	/*
	  In: Body
	*/
	Payload *models.KGW `json:"body,omitempty"`
}

// NewCreateProjectZoneKgwCreated creates CreateProjectZoneKgwCreated with default headers values
func NewCreateProjectZoneKgwCreated() *CreateProjectZoneKgwCreated {

	return &CreateProjectZoneKgwCreated{}
}

// WithPayload adds the payload to the create project zone kgw created response
func (o *CreateProjectZoneKgwCreated) WithPayload(payload *models.KGW) *CreateProjectZoneKgwCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create project zone kgw created response
func (o *CreateProjectZoneKgwCreated) SetPayload(payload *models.KGW) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProjectZoneKgwCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateProjectZoneKgwBadRequestCode is the HTTP code returned for type CreateProjectZoneKgwBadRequest
const CreateProjectZoneKgwBadRequestCode int = 400

/*
CreateProjectZoneKgwBadRequest Bad parameters were provided.

swagger:response createProjectZoneKgwBadRequest
*/
type CreateProjectZoneKgwBadRequest struct {
}

// NewCreateProjectZoneKgwBadRequest creates CreateProjectZoneKgwBadRequest with default headers values
func NewCreateProjectZoneKgwBadRequest() *CreateProjectZoneKgwBadRequest {

	return &CreateProjectZoneKgwBadRequest{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKgwBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateProjectZoneKgwNotFoundCode is the HTTP code returned for type CreateProjectZoneKgwNotFound
const CreateProjectZoneKgwNotFoundCode int = 404

/*
CreateProjectZoneKgwNotFound Invalid project or zone ID was provided.

swagger:response createProjectZoneKgwNotFound
*/
type CreateProjectZoneKgwNotFound struct {
}

// NewCreateProjectZoneKgwNotFound creates CreateProjectZoneKgwNotFound with default headers values
func NewCreateProjectZoneKgwNotFound() *CreateProjectZoneKgwNotFound {

	return &CreateProjectZoneKgwNotFound{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKgwNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateProjectZoneKgwConflictCode is the HTTP code returned for type CreateProjectZoneKgwConflict
const CreateProjectZoneKgwConflictCode int = 409

/*
CreateProjectZoneKgwConflict KGW already exists.

swagger:response createProjectZoneKgwConflict
*/
type CreateProjectZoneKgwConflict struct {
}

// NewCreateProjectZoneKgwConflict creates CreateProjectZoneKgwConflict with default headers values
func NewCreateProjectZoneKgwConflict() *CreateProjectZoneKgwConflict {

	return &CreateProjectZoneKgwConflict{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKgwConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateProjectZoneKgwInternalServerErrorCode is the HTTP code returned for type CreateProjectZoneKgwInternalServerError
const CreateProjectZoneKgwInternalServerErrorCode int = 500

/*
CreateProjectZoneKgwInternalServerError Unable to create the KGW.

swagger:response createProjectZoneKgwInternalServerError
*/
type CreateProjectZoneKgwInternalServerError struct {
}

// NewCreateProjectZoneKgwInternalServerError creates CreateProjectZoneKgwInternalServerError with default headers values
func NewCreateProjectZoneKgwInternalServerError() *CreateProjectZoneKgwInternalServerError {

	return &CreateProjectZoneKgwInternalServerError{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKgwInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
