// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// CreateZoneKceURL generates an URL for the create zone kce operation
type CreateZoneKceURL struct {
	ProjectID string
	ZoneID    string

	PoolID     *string
	Public     *bool
	SubnetID   *string
	TemplateID *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CreateZoneKceURL) WithBasePath(bp string) *CreateZoneKceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CreateZoneKceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *CreateZoneKceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/project/{projectId}/zone/{zoneId}/kce"

	projectID := o.ProjectID
	if projectID != "" {
		_path = strings.Replace(_path, "{projectId}", projectID, -1)
	} else {
		return nil, errors.New("projectId is required on CreateZoneKceURL")
	}

	zoneID := o.ZoneID
	if zoneID != "" {
		_path = strings.Replace(_path, "{zoneId}", zoneID, -1)
	} else {
		return nil, errors.New("zoneId is required on CreateZoneKceURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var poolIDQ string
	if o.PoolID != nil {
		poolIDQ = *o.PoolID
	}
	if poolIDQ != "" {
		qs.Set("poolId", poolIDQ)
	}

	var publicQ string
	if o.Public != nil {
		publicQ = swag.FormatBool(*o.Public)
	}
	if publicQ != "" {
		qs.Set("public", publicQ)
	}

	var subnetIDQ string
	if o.SubnetID != nil {
		subnetIDQ = *o.SubnetID
	}
	if subnetIDQ != "" {
		qs.Set("subnetId", subnetIDQ)
	}

	var templateIDQ string
	if o.TemplateID != nil {
		templateIDQ = *o.TemplateID
	}
	if templateIDQ != "" {
		qs.Set("templateId", templateIDQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CreateZoneKceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CreateZoneKceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CreateZoneKceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CreateZoneKceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CreateZoneKceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CreateZoneKceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
