// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/kowabunga-api/models"
)

// CreateProjectZoneKceCreatedCode is the HTTP code returned for type CreateProjectZoneKceCreated
const CreateProjectZoneKceCreatedCode int = 201

/*
CreateProjectZoneKceCreated Returns the newly created KCE virtual machine object.

swagger:response createProjectZoneKceCreated
*/
type CreateProjectZoneKceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.KCE `json:"body,omitempty"`
}

// NewCreateProjectZoneKceCreated creates CreateProjectZoneKceCreated with default headers values
func NewCreateProjectZoneKceCreated() *CreateProjectZoneKceCreated {

	return &CreateProjectZoneKceCreated{}
}

// WithPayload adds the payload to the create project zone kce created response
func (o *CreateProjectZoneKceCreated) WithPayload(payload *models.KCE) *CreateProjectZoneKceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create project zone kce created response
func (o *CreateProjectZoneKceCreated) SetPayload(payload *models.KCE) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProjectZoneKceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateProjectZoneKceBadRequestCode is the HTTP code returned for type CreateProjectZoneKceBadRequest
const CreateProjectZoneKceBadRequestCode int = 400

/*
CreateProjectZoneKceBadRequest Bad parameters were provided.

swagger:response createProjectZoneKceBadRequest
*/
type CreateProjectZoneKceBadRequest struct {
}

// NewCreateProjectZoneKceBadRequest creates CreateProjectZoneKceBadRequest with default headers values
func NewCreateProjectZoneKceBadRequest() *CreateProjectZoneKceBadRequest {

	return &CreateProjectZoneKceBadRequest{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateProjectZoneKceNotFoundCode is the HTTP code returned for type CreateProjectZoneKceNotFound
const CreateProjectZoneKceNotFoundCode int = 404

/*
CreateProjectZoneKceNotFound Invalid project or zone ID was provided.

swagger:response createProjectZoneKceNotFound
*/
type CreateProjectZoneKceNotFound struct {
}

// NewCreateProjectZoneKceNotFound creates CreateProjectZoneKceNotFound with default headers values
func NewCreateProjectZoneKceNotFound() *CreateProjectZoneKceNotFound {

	return &CreateProjectZoneKceNotFound{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateProjectZoneKceConflictCode is the HTTP code returned for type CreateProjectZoneKceConflict
const CreateProjectZoneKceConflictCode int = 409

/*
CreateProjectZoneKceConflict KCE Virtual machine already exists.

swagger:response createProjectZoneKceConflict
*/
type CreateProjectZoneKceConflict struct {
}

// NewCreateProjectZoneKceConflict creates CreateProjectZoneKceConflict with default headers values
func NewCreateProjectZoneKceConflict() *CreateProjectZoneKceConflict {

	return &CreateProjectZoneKceConflict{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKceConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// CreateProjectZoneKceInternalServerErrorCode is the HTTP code returned for type CreateProjectZoneKceInternalServerError
const CreateProjectZoneKceInternalServerErrorCode int = 500

/*
CreateProjectZoneKceInternalServerError Unable to create the KCE virtual machine.

swagger:response createProjectZoneKceInternalServerError
*/
type CreateProjectZoneKceInternalServerError struct {
}

// NewCreateProjectZoneKceInternalServerError creates CreateProjectZoneKceInternalServerError with default headers values
func NewCreateProjectZoneKceInternalServerError() *CreateProjectZoneKceInternalServerError {

	return &CreateProjectZoneKceInternalServerError{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// CreateProjectZoneKceInsufficientStorageCode is the HTTP code returned for type CreateProjectZoneKceInsufficientStorage
const CreateProjectZoneKceInsufficientStorageCode int = 507

/*
CreateProjectZoneKceInsufficientStorage Requested characteristics are beyond project's quota in place.

swagger:response createProjectZoneKceInsufficientStorage
*/
type CreateProjectZoneKceInsufficientStorage struct {
}

// NewCreateProjectZoneKceInsufficientStorage creates CreateProjectZoneKceInsufficientStorage with default headers values
func NewCreateProjectZoneKceInsufficientStorage() *CreateProjectZoneKceInsufficientStorage {

	return &CreateProjectZoneKceInsufficientStorage{}
}

// WriteResponse to the client
func (o *CreateProjectZoneKceInsufficientStorage) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(507)
}
