// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dalet-oss/kowabunga-api/models"
)

// GetProjectQuotasOKCode is the HTTP code returned for type GetProjectQuotasOK
const GetProjectQuotasOKCode int = 200

/*
GetProjectQuotasOK Returns the project resources object.

swagger:response getProjectQuotasOK
*/
type GetProjectQuotasOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProjectResources `json:"body,omitempty"`
}

// NewGetProjectQuotasOK creates GetProjectQuotasOK with default headers values
func NewGetProjectQuotasOK() *GetProjectQuotasOK {

	return &GetProjectQuotasOK{}
}

// WithPayload adds the payload to the get project quotas o k response
func (o *GetProjectQuotasOK) WithPayload(payload *models.ProjectResources) *GetProjectQuotasOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project quotas o k response
func (o *GetProjectQuotasOK) SetPayload(payload *models.ProjectResources) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectQuotasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProjectQuotasNotFoundCode is the HTTP code returned for type GetProjectQuotasNotFound
const GetProjectQuotasNotFoundCode int = 404

/*
GetProjectQuotasNotFound Invalid project ID was provided.

swagger:response getProjectQuotasNotFound
*/
type GetProjectQuotasNotFound struct {
}

// NewGetProjectQuotasNotFound creates GetProjectQuotasNotFound with default headers values
func NewGetProjectQuotasNotFound() *GetProjectQuotasNotFound {

	return &GetProjectQuotasNotFound{}
}

// WriteResponse to the client
func (o *GetProjectQuotasNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
