// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetProjectVolumesOKCode is the HTTP code returned for type GetProjectVolumesOK
const GetProjectVolumesOKCode int = 200

/*
GetProjectVolumesOK Returns an array of storage volume IDs.

swagger:response getProjectVolumesOK
*/
type GetProjectVolumesOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetProjectVolumesOK creates GetProjectVolumesOK with default headers values
func NewGetProjectVolumesOK() *GetProjectVolumesOK {

	return &GetProjectVolumesOK{}
}

// WithPayload adds the payload to the get project volumes o k response
func (o *GetProjectVolumesOK) WithPayload(payload []string) *GetProjectVolumesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project volumes o k response
func (o *GetProjectVolumesOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectVolumesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetProjectVolumesNotFoundCode is the HTTP code returned for type GetProjectVolumesNotFound
const GetProjectVolumesNotFoundCode int = 404

/*
GetProjectVolumesNotFound Invalid project ID was provided.

swagger:response getProjectVolumesNotFound
*/
type GetProjectVolumesNotFound struct {
}

// NewGetProjectVolumesNotFound creates GetProjectVolumesNotFound with default headers values
func NewGetProjectVolumesNotFound() *GetProjectVolumesNotFound {

	return &GetProjectVolumesNotFound{}
}

// WriteResponse to the client
func (o *GetProjectVolumesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
