// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateProjectQuotasHandlerFunc turns a function with the right signature into a update project quotas handler
type UpdateProjectQuotasHandlerFunc func(UpdateProjectQuotasParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateProjectQuotasHandlerFunc) Handle(params UpdateProjectQuotasParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateProjectQuotasHandler interface for that can handle valid update project quotas params
type UpdateProjectQuotasHandler interface {
	Handle(UpdateProjectQuotasParams, interface{}) middleware.Responder
}

// NewUpdateProjectQuotas creates a new http.Handler for the update project quotas operation
func NewUpdateProjectQuotas(ctx *middleware.Context, handler UpdateProjectQuotasHandler) *UpdateProjectQuotas {
	return &UpdateProjectQuotas{Context: ctx, Handler: handler}
}

/*
	UpdateProjectQuotas swagger:route PUT /project/{projectId}/quotas project updateProjectQuotas

Updates a project's quotas.
*/
type UpdateProjectQuotas struct {
	Context *middleware.Context
	Handler UpdateProjectQuotasHandler
}

func (o *UpdateProjectQuotas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateProjectQuotasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
