// Code generated by go-swagger; DO NOT EDIT.

package kce

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ResumeKCEHandlerFunc turns a function with the right signature into a resume k c e handler
type ResumeKCEHandlerFunc func(ResumeKCEParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ResumeKCEHandlerFunc) Handle(params ResumeKCEParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ResumeKCEHandler interface for that can handle valid resume k c e params
type ResumeKCEHandler interface {
	Handle(ResumeKCEParams, interface{}) middleware.Responder
}

// NewResumeKCE creates a new http.Handler for the resume k c e operation
func NewResumeKCE(ctx *middleware.Context, handler ResumeKCEHandler) *ResumeKCE {
	return &ResumeKCE{Context: ctx, Handler: handler}
}

/*
	ResumeKCE swagger:route POST /kce/{kceId}/resume kce resumeKCE

Perform a KCE virtual machine software PM resume.
*/
type ResumeKCE struct {
	Context *middleware.Context
	Handler ResumeKCEHandler
}

func (o *ResumeKCE) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewResumeKCEParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
