// Code generated by go-swagger; DO NOT EDIT.

package kce

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SuspendKCEOKCode is the HTTP code returned for type SuspendKCEOK
const SuspendKCEOKCode int = 200

/*
SuspendKCEOK The KCE virtual machine has been suspended successfully.

swagger:response suspendKCEOK
*/
type SuspendKCEOK struct {
}

// NewSuspendKCEOK creates SuspendKCEOK with default headers values
func NewSuspendKCEOK() *SuspendKCEOK {

	return &SuspendKCEOK{}
}

// WriteResponse to the client
func (o *SuspendKCEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SuspendKCENotFoundCode is the HTTP code returned for type SuspendKCENotFound
const SuspendKCENotFoundCode int = 404

/*
SuspendKCENotFound Invalid KCE ID was provided.

swagger:response suspendKCENotFound
*/
type SuspendKCENotFound struct {
}

// NewSuspendKCENotFound creates SuspendKCENotFound with default headers values
func NewSuspendKCENotFound() *SuspendKCENotFound {

	return &SuspendKCENotFound{}
}

// WriteResponse to the client
func (o *SuspendKCENotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SuspendKCEInternalServerErrorCode is the HTTP code returned for type SuspendKCEInternalServerError
const SuspendKCEInternalServerErrorCode int = 500

/*
SuspendKCEInternalServerError An error occurred when trying to suspend the KCE virtual machine.

swagger:response suspendKCEInternalServerError
*/
type SuspendKCEInternalServerError struct {
}

// NewSuspendKCEInternalServerError creates SuspendKCEInternalServerError with default headers values
func NewSuspendKCEInternalServerError() *SuspendKCEInternalServerError {

	return &SuspendKCEInternalServerError{}
}

// WriteResponse to the client
func (o *SuspendKCEInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
