// Code generated by go-swagger; DO NOT EDIT.

package nfs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAllNfsStoragesOKCode is the HTTP code returned for type GetAllNfsStoragesOK
const GetAllNfsStoragesOKCode int = 200

/*
GetAllNfsStoragesOK Returns the an array of NFS storage IDs.

swagger:response getAllNfsStoragesOK
*/
type GetAllNfsStoragesOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetAllNfsStoragesOK creates GetAllNfsStoragesOK with default headers values
func NewGetAllNfsStoragesOK() *GetAllNfsStoragesOK {

	return &GetAllNfsStoragesOK{}
}

// WithPayload adds the payload to the get all nfs storages o k response
func (o *GetAllNfsStoragesOK) WithPayload(payload []string) *GetAllNfsStoragesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all nfs storages o k response
func (o *GetAllNfsStoragesOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllNfsStoragesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
