/**
 * Kowabunga
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the host CPU characteristics
 */
export interface HostCapsCpu { 
    /**
     * the host CPU architecture
     */
    arch: string;
    /**
     * the host CPU model
     */
    model: string;
    /**
     * the host CPU vendor
     */
    vendor: string;
    /**
     * the host CPU number of sockets
     */
    sockets: number;
    /**
     * the host CPU number of cores
     */
    cores: number;
    /**
     * the host CPU number of threads
     */
    threads: number;
}

