/**
 * Kowabunga
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The host libvirt\'s TLS configuration.
 */
export interface HostTls { 
    /**
     * The TLS client private key.
     */
    key: string;
    /**
     * The TLS client public cert.
     */
    cert: string;
    /**
     * The TLS certificate of authority.
     */
    ca: string;
}

