// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetZonePoolsHandlerFunc turns a function with the right signature into a get zone pools handler
type GetZonePoolsHandlerFunc func(GetZonePoolsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetZonePoolsHandlerFunc) Handle(params GetZonePoolsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetZonePoolsHandler interface for that can handle valid get zone pools params
type GetZonePoolsHandler interface {
	Handle(GetZonePoolsParams, interface{}) middleware.Responder
}

// NewGetZonePools creates a new http.Handler for the get zone pools operation
func NewGetZonePools(ctx *middleware.Context, handler GetZonePoolsHandler) *GetZonePools {
	return &GetZonePools{Context: ctx, Handler: handler}
}

/*
	GetZonePools swagger:route GET /zone/{zoneId}/pools zone pool getZonePools

Returns the IDs of the pools existing in the zone.
*/
type GetZonePools struct {
	Context *middleware.Context
	Handler GetZonePoolsHandler
}

func (o *GetZonePools) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetZonePoolsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
