/*
Kowabunga API documentation

Kvm Orchestrator With A BUNch of Goods Added

API version: 0.39.0
Contact: csops@dalet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Host type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Host{}

// Host A computing host.
type Host struct {
	// The computing host ID (auto-generated).
	Id *string `json:"id,omitempty"`
	// The computing host name.
	Name string `json:"name"`
	// The computing host description.
	Description *string `json:"description,omitempty"`
	// Cost associated to the host's CPU resources.
	CpuCost Cost `json:"cpu_cost,omitempty"`
	// Cost associated to the host's memoery resources.
	MemoryCost Cost `json:"memory_cost,omitempty"`
	// The host CPU resource over-commit ratio. Overcommitting CPU resources for VMs means allocating more virtual CPUs (vCPUs) to the virtual machines (VMs) than the physical cores available on the host. This can help optimize the utilization of the host CPU and increase the density of VMs per host.
	OvercommitCpuRatio *int64 `json:"overcommit_cpu_ratio,omitempty"`
	// The host memory resource over-commit ratio. Memory overcommitment is a concept in computing that covers the assignment of more memory to virtual computing devices (or processes) than the physical machine they are hosted, or running on, actually has.
	OvercommitMemoryRatio *int64 `json:"overcommit_memory_ratio,omitempty"`
	// a list of existing remote agents managing the host.
	Agents []string `json:"agents"`
}

type _Host Host

// NewHost instantiates a new Host object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHost(name string, agents []string) *Host {
	this := Host{}
	this.Name = name
	var overcommitCpuRatio int64 = 3
	this.OvercommitCpuRatio = &overcommitCpuRatio
	var overcommitMemoryRatio int64 = 2
	this.OvercommitMemoryRatio = &overcommitMemoryRatio
	this.Agents = agents
	return &this
}

// NewHostWithDefaults instantiates a new Host object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostWithDefaults() *Host {
	this := Host{}
	var overcommitCpuRatio int64 = 3
	this.OvercommitCpuRatio = &overcommitCpuRatio
	var overcommitMemoryRatio int64 = 2
	this.OvercommitMemoryRatio = &overcommitMemoryRatio
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Host) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Host) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Host) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *Host) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Host) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Host) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Host) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Host) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Host) SetDescription(v string) {
	o.Description = &v
}

// GetCpuCost returns the CpuCost field value if set, zero value otherwise.
func (o *Host) GetCpuCost() Cost {
	if o == nil || IsNil(o.CpuCost) {
		var ret Cost
		return ret
	}
	return o.CpuCost
}

// GetCpuCostOk returns a tuple with the CpuCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetCpuCostOk() (Cost, bool) {
	if o == nil || IsNil(o.CpuCost) {
		return Cost{}, false
	}
	return o.CpuCost, true
}

// HasCpuCost returns a boolean if a field has been set.
func (o *Host) HasCpuCost() bool {
	if o != nil && !IsNil(o.CpuCost) {
		return true
	}

	return false
}

// SetCpuCost gets a reference to the given Cost and assigns it to the CpuCost field.
func (o *Host) SetCpuCost(v Cost) {
	o.CpuCost = v
}

// GetMemoryCost returns the MemoryCost field value if set, zero value otherwise.
func (o *Host) GetMemoryCost() Cost {
	if o == nil || IsNil(o.MemoryCost) {
		var ret Cost
		return ret
	}
	return o.MemoryCost
}

// GetMemoryCostOk returns a tuple with the MemoryCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetMemoryCostOk() (Cost, bool) {
	if o == nil || IsNil(o.MemoryCost) {
		return Cost{}, false
	}
	return o.MemoryCost, true
}

// HasMemoryCost returns a boolean if a field has been set.
func (o *Host) HasMemoryCost() bool {
	if o != nil && !IsNil(o.MemoryCost) {
		return true
	}

	return false
}

// SetMemoryCost gets a reference to the given Cost and assigns it to the MemoryCost field.
func (o *Host) SetMemoryCost(v Cost) {
	o.MemoryCost = v
}

// GetOvercommitCpuRatio returns the OvercommitCpuRatio field value if set, zero value otherwise.
func (o *Host) GetOvercommitCpuRatio() int64 {
	if o == nil || IsNil(o.OvercommitCpuRatio) {
		var ret int64
		return ret
	}
	return *o.OvercommitCpuRatio
}

// GetOvercommitCpuRatioOk returns a tuple with the OvercommitCpuRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetOvercommitCpuRatioOk() (*int64, bool) {
	if o == nil || IsNil(o.OvercommitCpuRatio) {
		return nil, false
	}
	return o.OvercommitCpuRatio, true
}

// HasOvercommitCpuRatio returns a boolean if a field has been set.
func (o *Host) HasOvercommitCpuRatio() bool {
	if o != nil && !IsNil(o.OvercommitCpuRatio) {
		return true
	}

	return false
}

// SetOvercommitCpuRatio gets a reference to the given int64 and assigns it to the OvercommitCpuRatio field.
func (o *Host) SetOvercommitCpuRatio(v int64) {
	o.OvercommitCpuRatio = &v
}

// GetOvercommitMemoryRatio returns the OvercommitMemoryRatio field value if set, zero value otherwise.
func (o *Host) GetOvercommitMemoryRatio() int64 {
	if o == nil || IsNil(o.OvercommitMemoryRatio) {
		var ret int64
		return ret
	}
	return *o.OvercommitMemoryRatio
}

// GetOvercommitMemoryRatioOk returns a tuple with the OvercommitMemoryRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetOvercommitMemoryRatioOk() (*int64, bool) {
	if o == nil || IsNil(o.OvercommitMemoryRatio) {
		return nil, false
	}
	return o.OvercommitMemoryRatio, true
}

// HasOvercommitMemoryRatio returns a boolean if a field has been set.
func (o *Host) HasOvercommitMemoryRatio() bool {
	if o != nil && !IsNil(o.OvercommitMemoryRatio) {
		return true
	}

	return false
}

// SetOvercommitMemoryRatio gets a reference to the given int64 and assigns it to the OvercommitMemoryRatio field.
func (o *Host) SetOvercommitMemoryRatio(v int64) {
	o.OvercommitMemoryRatio = &v
}

// GetAgents returns the Agents field value
func (o *Host) GetAgents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value
// and a boolean to check if the value has been set.
func (o *Host) GetAgentsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Agents, true
}

// SetAgents sets field value
func (o *Host) SetAgents(v []string) {
	o.Agents = v
}

func (o Host) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Host) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CpuCost) {
		toSerialize["cpu_cost"] = o.CpuCost
	}
	if !IsNil(o.MemoryCost) {
		toSerialize["memory_cost"] = o.MemoryCost
	}
	if !IsNil(o.OvercommitCpuRatio) {
		toSerialize["overcommit_cpu_ratio"] = o.OvercommitCpuRatio
	}
	if !IsNil(o.OvercommitMemoryRatio) {
		toSerialize["overcommit_memory_ratio"] = o.OvercommitMemoryRatio
	}
	toSerialize["agents"] = o.Agents
	return toSerialize, nil
}

func (o *Host) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"agents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHost := _Host{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHost)

	if err != nil {
		return err
	}

	*o = Host(varHost)

	return err
}

type NullableHost struct {
	value *Host
	isSet bool
}

func (v NullableHost) Get() *Host {
	return v.value
}

func (v *NullableHost) Set(val *Host) {
	v.value = val
	v.isSet = true
}

func (v NullableHost) IsSet() bool {
	return v.isSet
}

func (v *NullableHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHost(val *Host) *NullableHost {
	return &NullableHost{value: val, isSet: true}
}

func (v NullableHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


