// Code generated by go-swagger; DO NOT EDIT.

package netgw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteNetGWHandlerFunc turns a function with the right signature into a delete net g w handler
type DeleteNetGWHandlerFunc func(DeleteNetGWParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNetGWHandlerFunc) Handle(params DeleteNetGWParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteNetGWHandler interface for that can handle valid delete net g w params
type DeleteNetGWHandler interface {
	Handle(DeleteNetGWParams, interface{}) middleware.Responder
}

// NewDeleteNetGW creates a new http.Handler for the delete net g w operation
func NewDeleteNetGW(ctx *middleware.Context, handler DeleteNetGWHandler) *DeleteNetGW {
	return &DeleteNetGW{Context: ctx, Handler: handler}
}

/*
	DeleteNetGW swagger:route DELETE /netgw/{netgwId} netgw deleteNetGW

Deletes an existing network gateway.
*/
type DeleteNetGW struct {
	Context *middleware.Context
	Handler DeleteNetGWHandler
}

func (o *DeleteNetGW) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteNetGWParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
