// Code generated by go-swagger; DO NOT EDIT.

package subnet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateAdapterHandlerFunc turns a function with the right signature into a create adapter handler
type CreateAdapterHandlerFunc func(CreateAdapterParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAdapterHandlerFunc) Handle(params CreateAdapterParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateAdapterHandler interface for that can handle valid create adapter params
type CreateAdapterHandler interface {
	Handle(CreateAdapterParams, interface{}) middleware.Responder
}

// NewCreateAdapter creates a new http.Handler for the create adapter operation
func NewCreateAdapter(ctx *middleware.Context, handler CreateAdapterHandler) *CreateAdapter {
	return &CreateAdapter{Context: ctx, Handler: handler}
}

/*
	CreateAdapter swagger:route POST /subnet/{subnetId}/adapter subnet adapter createAdapter

Creates a new network adapter.
*/
type CreateAdapter struct {
	Context *middleware.Context
	Handler CreateAdapterHandler
}

func (o *CreateAdapter) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateAdapterParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
