// Code generated by go-swagger; DO NOT EDIT.

package kce

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dalet-oss/kowabunga-api/models"
)

// NewUpdateKCEParams creates a new UpdateKCEParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateKCEParams() *UpdateKCEParams {
	return &UpdateKCEParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateKCEParamsWithTimeout creates a new UpdateKCEParams object
// with the ability to set a timeout on a request.
func NewUpdateKCEParamsWithTimeout(timeout time.Duration) *UpdateKCEParams {
	return &UpdateKCEParams{
		timeout: timeout,
	}
}

// NewUpdateKCEParamsWithContext creates a new UpdateKCEParams object
// with the ability to set a context for a request.
func NewUpdateKCEParamsWithContext(ctx context.Context) *UpdateKCEParams {
	return &UpdateKCEParams{
		Context: ctx,
	}
}

// NewUpdateKCEParamsWithHTTPClient creates a new UpdateKCEParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateKCEParamsWithHTTPClient(client *http.Client) *UpdateKCEParams {
	return &UpdateKCEParams{
		HTTPClient: client,
	}
}

/*
UpdateKCEParams contains all the parameters to send to the API endpoint

	for the update k c e operation.

	Typically these are written to a http.Request.
*/
type UpdateKCEParams struct {

	// Body.
	Body *models.KCE

	/* KceID.

	   The ID of the KCE virtual machine object.
	*/
	KceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update k c e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateKCEParams) WithDefaults() *UpdateKCEParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update k c e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateKCEParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update k c e params
func (o *UpdateKCEParams) WithTimeout(timeout time.Duration) *UpdateKCEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update k c e params
func (o *UpdateKCEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update k c e params
func (o *UpdateKCEParams) WithContext(ctx context.Context) *UpdateKCEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update k c e params
func (o *UpdateKCEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update k c e params
func (o *UpdateKCEParams) WithHTTPClient(client *http.Client) *UpdateKCEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update k c e params
func (o *UpdateKCEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update k c e params
func (o *UpdateKCEParams) WithBody(body *models.KCE) *UpdateKCEParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update k c e params
func (o *UpdateKCEParams) SetBody(body *models.KCE) {
	o.Body = body
}

// WithKceID adds the kceID to the update k c e params
func (o *UpdateKCEParams) WithKceID(kceID string) *UpdateKCEParams {
	o.SetKceID(kceID)
	return o
}

// SetKceID adds the kceId to the update k c e params
func (o *UpdateKCEParams) SetKceID(kceID string) {
	o.KceID = kceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateKCEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param kceId
	if err := r.SetPathParam("kceId", o.KceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
