// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAllProjectsOKCode is the HTTP code returned for type GetAllProjectsOK
const GetAllProjectsOKCode int = 200

/*
GetAllProjectsOK Returns the an array of project IDs.

swagger:response getAllProjectsOK
*/
type GetAllProjectsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetAllProjectsOK creates GetAllProjectsOK with default headers values
func NewGetAllProjectsOK() *GetAllProjectsOK {

	return &GetAllProjectsOK{}
}

// WithPayload adds the payload to the get all projects o k response
func (o *GetAllProjectsOK) WithPayload(payload []string) *GetAllProjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all projects o k response
func (o *GetAllProjectsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllProjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
