// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetProjectZoneKfsOKCode is the HTTP code returned for type GetProjectZoneKfsOK
const GetProjectZoneKfsOKCode int = 200

/*
GetProjectZoneKfsOK Returns an array of KFS storage volume IDs.

swagger:response getProjectZoneKfsOK
*/
type GetProjectZoneKfsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetProjectZoneKfsOK creates GetProjectZoneKfsOK with default headers values
func NewGetProjectZoneKfsOK() *GetProjectZoneKfsOK {

	return &GetProjectZoneKfsOK{}
}

// WithPayload adds the payload to the get project zone kfs o k response
func (o *GetProjectZoneKfsOK) WithPayload(payload []string) *GetProjectZoneKfsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project zone kfs o k response
func (o *GetProjectZoneKfsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectZoneKfsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetProjectZoneKfsNotFoundCode is the HTTP code returned for type GetProjectZoneKfsNotFound
const GetProjectZoneKfsNotFoundCode int = 404

/*
GetProjectZoneKfsNotFound Invalid project or zone ID was provided.

swagger:response getProjectZoneKfsNotFound
*/
type GetProjectZoneKfsNotFound struct {
}

// NewGetProjectZoneKfsNotFound creates GetProjectZoneKfsNotFound with default headers values
func NewGetProjectZoneKfsNotFound() *GetProjectZoneKfsNotFound {

	return &GetProjectZoneKfsNotFound{}
}

// WriteResponse to the client
func (o *GetProjectZoneKfsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
